// String constants only. Imported by the preload, so it must stay free of zod and Node.
export const INVOKE_CHANNELS = [
  'app:getInfo',
  'app:showDataFolder',
  'app:quit',
  'settings:get',
  'settings:set',
  'capabilities:get',
  'tree:list',
  'project:create',
  'project:rename',
  'project:trash',
  'folder:create',
  'folder:rename',
  'folder:move',
  'folder:trash',
  'note:create',
  'note:rename',
  'note:move',
  'note:trash',
  'note:setPinned',
  'item:setFavorite',
  'trash:list',
  'trash:restore',
  'trash:purge',
  'home:summary',
  'session:get',
  'session:set',
  'palette:searchTitles',
  'note:open',
  'note:save',
  'lease:acquire',
  'lease:release',
  'lease:take',
  'note:convertFormat',
  'versions:list',
  'versions:restore',
  'drafts:list',
  'drafts:resolve',
  'attachment:importBytes',
  'attachment:importFromDialog',
  'shell:openExternal',
  'app:flushed',
  'sticky:float',
  'sticky:dock',
  'sticky:hide',
  'sticky:setColor',
  'sticky:setPinned',
  'sticky:setCollapsed',
  'sticky:remove',
  'sticky:restore',
  'window:getState',
] as const;

export const EVENT_CHANNELS = [
  'settings:changed',
  'tree:changed',
  'note:revision',
  'note:lease',
  'lease:release-request',
  'app:flush-request',
  'sticky:state',
  'app:openNote',
] as const;

export type InvokeChannel = (typeof INVOKE_CHANNELS)[number];
export type EventChannel = (typeof EVENT_CHANNELS)[number];
